### PR TITLE
Miscellaneous fixes

### PR DESCRIPTION
**Pull request by sschuberth**

### CODE REVIEW

**Comment by sschuberth** [comment]
@jbaruch Would you have some time to look at this?

**Comment by jbaruch** [comment]
We are on it, thanks!

**Comment by sschuberth** [comment]
@jbaruch Any update?

**Comment by sschuberth** [comment]
@jbaruch Half a year has passed. How much longer are you going to be "on it"? ;-)

**Comment by sschuberth** [comment]
I just realized @shayke has authored most of the file. May you could have a look?

**Comment by eyalbe4** [comment]
@sschuberth , I can merge this PR and I really apologize it hasn't been handled sooner.
Can you please sign the CLA through the following link so that I can merge your code?
http://www.jfrog.com/confluence/display/OSS/How+to+Contribute

**Comment by sschuberth** [comment]
@eyalbe4 Done!

**Pull request merged**
